FROM ros:humble-ros-base-jammy

RUN apt-get -y update \
    && apt-get -y install vim \
    ros-humble-rmw-cyclonedds-cpp ros-dev-tools\ 
    python3 python3-pip python3-venv \
    curl iputils-ping netcat dnsutils net-tools \
    && apt-get -qq -y autoremove \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* /var/log/dpkg.log
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

COPY ../app/ /app/

WORKDIR /app
ENTRYPOINT ["/bin/bash", "-c"]
CMD ["tail -f /dev/null"]